#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlitiembanh.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quanlitiembanhmi")]
	public partial class QuanlitiembanhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertvoucher(voucher instance);
    partial void Updatevoucher(voucher instance);
    partial void Deletevoucher(voucher instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public QuanlitiembanhDataContext() : 
				base(global::Quanlitiembanh.Properties.Settings.Default.QuanlitiembanhmiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlitiembanhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlitiembanhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlitiembanhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlitiembanhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<voucher> vouchers
		{
			get
			{
				return this.GetTable<voucher>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitietsanpham")]
		public ISingleResult<chitietsanphamResult> chitietsanpham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<chitietsanphamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoasanpham")]
		public int xoasanpham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.kiemtravoucher")]
		public ISingleResult<kiemtravoucherResult> kiemtravoucher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string voucher)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), voucher);
			return ((ISingleResult<kiemtravoucherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laydanhsachsanpham")]
		public ISingleResult<laydanhsachsanphamResult> laydanhsachsanpham()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<laydanhsachsanphamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suasanpham")]
		public int suasanpham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tensanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> giatien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string mota, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string hinhanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tensanpham, giatien, mota, soluong, hinhanh, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.taohoadon")]
		public int taohoadon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tenkhachhang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string sdtkhachhang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> magiamgia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_sanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaythem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tongtien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenkhachhang, sdtkhachhang, magiamgia, id_sanpham, soluong, ngaythem, ngaycapnhat, tongtien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themsanpham")]
		public int themsanpham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tensanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> giatien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string mota, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string hinhanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaythem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tensanpham, giatien, mota, hinhanh, soluong, ngaythem, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themvoucher")]
		public int themvoucher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tenvoucher, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string mavoucher, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hoadontoithieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> giamgiatoida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaybatdau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayketthuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaythem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenvoucher, mavoucher, hoadontoithieu, giamgiatoida, ngaybatdau, ngayketthuc, ngaythem, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timsanpham")]
		public ISingleResult<timsanphamResult> timsanpham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tim)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tim);
			return ((ISingleResult<timsanphamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoahoadon")]
		public int xoahoadon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoavoucher")]
		public int xoavoucher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suavoucher")]
		public int suavoucher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tenvoucher, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string mavoucher, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaybatdau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayketthuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hoadontoithieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> giamgiatoida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tenvoucher, mavoucher, ngaybatdau, ngayketthuc, hoadontoithieu, giamgiatoida, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timvoucher")]
		public ISingleResult<timvoucherResult> timvoucher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tim)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tim);
			return ((ISingleResult<timvoucherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laytatcahoadon")]
		public ISingleResult<laytatcahoadonResult> laytatcahoadon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<laytatcahoadonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laydulieuvoucher")]
		public ISingleResult<laydulieuvoucherResult> laydulieuvoucher()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<laydulieuvoucherResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dangkytaikhoan")]
		public int dangkytaikhoan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tendangnhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string matkhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tenhienthi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaytao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tendangnhap, matkhau, tenhienthi, ngaytao, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenkhachhang;
		
		private string _sdtkhachhang;
		
		private System.Nullable<int> _magiamgia;
		
		private System.Nullable<int> _id_sanpham;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _tongtien;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private EntityRef<voucher> _voucher;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenkhachhangChanging(string value);
    partial void OntenkhachhangChanged();
    partial void OnsdtkhachhangChanging(string value);
    partial void OnsdtkhachhangChanged();
    partial void OnmagiamgiaChanging(System.Nullable<int> value);
    partial void OnmagiamgiaChanged();
    partial void Onid_sanphamChanging(System.Nullable<int> value);
    partial void Onid_sanphamChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OntongtienChanging(System.Nullable<double> value);
    partial void OntongtienChanged();
    partial void OnngaythemChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythemChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    #endregion
		
		public hoadon()
		{
			this._voucher = default(EntityRef<voucher>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="NVarChar(255)")]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this.OntenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._tenkhachhang = value;
					this.SendPropertyChanged("tenkhachhang");
					this.OntenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtkhachhang", DbType="NVarChar(255)")]
		public string sdtkhachhang
		{
			get
			{
				return this._sdtkhachhang;
			}
			set
			{
				if ((this._sdtkhachhang != value))
				{
					this.OnsdtkhachhangChanging(value);
					this.SendPropertyChanging();
					this._sdtkhachhang = value;
					this.SendPropertyChanged("sdtkhachhang");
					this.OnsdtkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magiamgia", DbType="Int")]
		public System.Nullable<int> magiamgia
		{
			get
			{
				return this._magiamgia;
			}
			set
			{
				if ((this._magiamgia != value))
				{
					if (this._voucher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmagiamgiaChanging(value);
					this.SendPropertyChanging();
					this._magiamgia = value;
					this.SendPropertyChanged("magiamgia");
					this.OnmagiamgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", DbType="Int")]
		public System.Nullable<int> id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this.OnngaythemChanging(value);
					this.SendPropertyChanging();
					this._ngaythem = value;
					this.SendPropertyChanged("ngaythem");
					this.OnngaythemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="voucher_hoadon", Storage="_voucher", ThisKey="magiamgia", OtherKey="id", IsForeignKey=true)]
		public voucher voucher
		{
			get
			{
				return this._voucher.Entity;
			}
			set
			{
				voucher previousValue = this._voucher.Entity;
				if (((previousValue != value) 
							|| (this._voucher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._voucher.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._voucher.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._magiamgia = value.id;
					}
					else
					{
						this._magiamgia = default(Nullable<int>);
					}
					this.SendPropertyChanged("voucher");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_hoadon", Storage="_sanpham", ThisKey="id_sanpham", OtherKey="id", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._id_sanpham = value.id;
					}
					else
					{
						this._id_sanpham = default(Nullable<int>);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.voucher")]
	public partial class voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenvoucher;
		
		private string _mavoucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<double> _hoadontoithieu;
		
		private System.Nullable<double> _giamgiatoida;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenvoucherChanging(string value);
    partial void OntenvoucherChanged();
    partial void OnmavoucherChanging(string value);
    partial void OnmavoucherChanged();
    partial void OnngaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybatdauChanged();
    partial void OnngayketthucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayketthucChanged();
    partial void OnhoadontoithieuChanging(System.Nullable<double> value);
    partial void OnhoadontoithieuChanged();
    partial void OngiamgiatoidaChanging(System.Nullable<double> value);
    partial void OngiamgiatoidaChanged();
    partial void OnngaythemChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythemChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    #endregion
		
		public voucher()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="NVarChar(255)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this.OntenvoucherChanging(value);
					this.SendPropertyChanging();
					this._tenvoucher = value;
					this.SendPropertyChanged("tenvoucher");
					this.OntenvoucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavoucher", DbType="VarChar(255)")]
		public string mavoucher
		{
			get
			{
				return this._mavoucher;
			}
			set
			{
				if ((this._mavoucher != value))
				{
					this.OnmavoucherChanging(value);
					this.SendPropertyChanging();
					this._mavoucher = value;
					this.SendPropertyChanged("mavoucher");
					this.OnmavoucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this.OnngaybatdauChanging(value);
					this.SendPropertyChanging();
					this._ngaybatdau = value;
					this.SendPropertyChanged("ngaybatdau");
					this.OnngaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this.OnngayketthucChanging(value);
					this.SendPropertyChanging();
					this._ngayketthuc = value;
					this.SendPropertyChanged("ngayketthuc");
					this.OnngayketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadontoithieu", DbType="Float")]
		public System.Nullable<double> hoadontoithieu
		{
			get
			{
				return this._hoadontoithieu;
			}
			set
			{
				if ((this._hoadontoithieu != value))
				{
					this.OnhoadontoithieuChanging(value);
					this.SendPropertyChanging();
					this._hoadontoithieu = value;
					this.SendPropertyChanged("hoadontoithieu");
					this.OnhoadontoithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgiatoida", DbType="Float")]
		public System.Nullable<double> giamgiatoida
		{
			get
			{
				return this._giamgiatoida;
			}
			set
			{
				if ((this._giamgiatoida != value))
				{
					this.OngiamgiatoidaChanging(value);
					this.SendPropertyChanging();
					this._giamgiatoida = value;
					this.SendPropertyChanged("giamgiatoida");
					this.OngiamgiatoidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this.OnngaythemChanging(value);
					this.SendPropertyChanging();
					this._ngaythem = value;
					this.SendPropertyChanged("ngaythem");
					this.OnngaythemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="voucher_hoadon", Storage="_hoadons", ThisKey="id", OtherKey="magiamgia")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.voucher = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.voucher = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tensanpham;
		
		private System.Nullable<double> _giatien;
		
		private string _mota;
		
		private string _hinhanh;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _soluong;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntensanphamChanging(string value);
    partial void OntensanphamChanged();
    partial void OngiatienChanging(System.Nullable<double> value);
    partial void OngiatienChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnngaythemChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythemChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public sanpham()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(255)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this.OntensanphamChanging(value);
					this.SendPropertyChanging();
					this._tensanpham = value;
					this.SendPropertyChanged("tensanpham");
					this.OntensanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Float")]
		public System.Nullable<double> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this.OngiatienChanging(value);
					this.SendPropertyChanging();
					this._giatien = value;
					this.SendPropertyChanged("giatien");
					this.OngiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this.OnngaythemChanging(value);
					this.SendPropertyChanging();
					this._ngaythem = value;
					this.SendPropertyChanged("ngaythem");
					this.OnngaythemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_hoadon", Storage="_hoadons", ThisKey="id", OtherKey="id_sanpham")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private string _tenhienthi;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OntenhienthiChanging(string value);
    partial void OntenhienthiChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="VarChar(255)")]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(255)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenhienthi", DbType="NVarChar(255)")]
		public string tenhienthi
		{
			get
			{
				return this._tenhienthi;
			}
			set
			{
				if ((this._tenhienthi != value))
				{
					this.OntenhienthiChanging(value);
					this.SendPropertyChanging();
					this._tenhienthi = value;
					this.SendPropertyChanged("tenhienthi");
					this.OntenhienthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class chitietsanphamResult
	{
		
		private int _id;
		
		private string _tensanpham;
		
		private System.Nullable<double> _giatien;
		
		private string _mota;
		
		private string _hinhanh;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _soluong;
		
		public chitietsanphamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(255)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this._tensanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Float")]
		public System.Nullable<double> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this._giatien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this._hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class kiemtravoucherResult
	{
		
		private int _id;
		
		private string _tenvoucher;
		
		private string _mavoucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<double> _hoadontoithieu;
		
		private System.Nullable<double> _giamgiatoida;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		public kiemtravoucherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="NVarChar(255)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this._tenvoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavoucher", DbType="VarChar(255)")]
		public string mavoucher
		{
			get
			{
				return this._mavoucher;
			}
			set
			{
				if ((this._mavoucher != value))
				{
					this._mavoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this._ngaybatdau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this._ngayketthuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadontoithieu", DbType="Float")]
		public System.Nullable<double> hoadontoithieu
		{
			get
			{
				return this._hoadontoithieu;
			}
			set
			{
				if ((this._hoadontoithieu != value))
				{
					this._hoadontoithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgiatoida", DbType="Float")]
		public System.Nullable<double> giamgiatoida
		{
			get
			{
				return this._giamgiatoida;
			}
			set
			{
				if ((this._giamgiatoida != value))
				{
					this._giamgiatoida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
	}
	
	public partial class laydanhsachsanphamResult
	{
		
		private System.Nullable<long> _stt;
		
		private int _id;
		
		private string _tensanpham;
		
		private System.Nullable<double> _giatien;
		
		private string _mota;
		
		private string _hinhanh;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _soluong;
		
		public laydanhsachsanphamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stt", DbType="BigInt")]
		public System.Nullable<long> stt
		{
			get
			{
				return this._stt;
			}
			set
			{
				if ((this._stt != value))
				{
					this._stt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(255)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this._tensanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Float")]
		public System.Nullable<double> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this._giatien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this._hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class timsanphamResult
	{
		
		private int _id;
		
		private string _tensanpham;
		
		private System.Nullable<double> _giatien;
		
		private string _mota;
		
		private string _hinhanh;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _soluong;
		
		public timsanphamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(255)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this._tensanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Float")]
		public System.Nullable<double> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this._giatien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this._hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class timvoucherResult
	{
		
		private int _id;
		
		private string _tenvoucher;
		
		private string _mavoucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<double> _hoadontoithieu;
		
		private System.Nullable<double> _giamgiatoida;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		public timvoucherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="NVarChar(255)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this._tenvoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavoucher", DbType="VarChar(255)")]
		public string mavoucher
		{
			get
			{
				return this._mavoucher;
			}
			set
			{
				if ((this._mavoucher != value))
				{
					this._mavoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this._ngaybatdau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this._ngayketthuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadontoithieu", DbType="Float")]
		public System.Nullable<double> hoadontoithieu
		{
			get
			{
				return this._hoadontoithieu;
			}
			set
			{
				if ((this._hoadontoithieu != value))
				{
					this._hoadontoithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgiatoida", DbType="Float")]
		public System.Nullable<double> giamgiatoida
		{
			get
			{
				return this._giamgiatoida;
			}
			set
			{
				if ((this._giamgiatoida != value))
				{
					this._giamgiatoida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
	}
	
	public partial class laytatcahoadonResult
	{
		
		private int _idhoadon;
		
		private int _id;
		
		private string _tenkhachhang;
		
		private string _sdtkhachhang;
		
		private System.Nullable<int> _magiamgia;
		
		private System.Nullable<int> _id_sanpham;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _tongtien;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private int _id1;
		
		private string _tensanpham;
		
		private System.Nullable<double> _giatien;
		
		private string _mota;
		
		private string _hinhanh;
		
		private System.Nullable<System.DateTime> _ngaythem1;
		
		private System.Nullable<System.DateTime> _ngaycapnhat1;
		
		private System.Nullable<int> _soluong1;
		
		private int _id2;
		
		private string _tenvoucher;
		
		private string _mavoucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<double> _hoadontoithieu;
		
		private System.Nullable<double> _giamgiatoida;
		
		private System.Nullable<System.DateTime> _ngaythem2;
		
		private System.Nullable<System.DateTime> _ngaycapnhat2;
		
		public laytatcahoadonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhoadon", DbType="Int NOT NULL")]
		public int idhoadon
		{
			get
			{
				return this._idhoadon;
			}
			set
			{
				if ((this._idhoadon != value))
				{
					this._idhoadon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="NVarChar(255)")]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this._tenkhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtkhachhang", DbType="NVarChar(255)")]
		public string sdtkhachhang
		{
			get
			{
				return this._sdtkhachhang;
			}
			set
			{
				if ((this._sdtkhachhang != value))
				{
					this._sdtkhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magiamgia", DbType="Int")]
		public System.Nullable<int> magiamgia
		{
			get
			{
				return this._magiamgia;
			}
			set
			{
				if ((this._magiamgia != value))
				{
					this._magiamgia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", DbType="Int")]
		public System.Nullable<int> id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					this._id_sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this._tongtien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id1", DbType="Int NOT NULL")]
		public int id1
		{
			get
			{
				return this._id1;
			}
			set
			{
				if ((this._id1 != value))
				{
					this._id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensanpham", DbType="NVarChar(255)")]
		public string tensanpham
		{
			get
			{
				return this._tensanpham;
			}
			set
			{
				if ((this._tensanpham != value))
				{
					this._tensanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Float")]
		public System.Nullable<double> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this._giatien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(255)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this._hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem1
		{
			get
			{
				return this._ngaythem1;
			}
			set
			{
				if ((this._ngaythem1 != value))
				{
					this._ngaythem1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat1
		{
			get
			{
				return this._ngaycapnhat1;
			}
			set
			{
				if ((this._ngaycapnhat1 != value))
				{
					this._ngaycapnhat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong1", DbType="Int")]
		public System.Nullable<int> soluong1
		{
			get
			{
				return this._soluong1;
			}
			set
			{
				if ((this._soluong1 != value))
				{
					this._soluong1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id2", DbType="Int NOT NULL")]
		public int id2
		{
			get
			{
				return this._id2;
			}
			set
			{
				if ((this._id2 != value))
				{
					this._id2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="NVarChar(255)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this._tenvoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavoucher", DbType="VarChar(255)")]
		public string mavoucher
		{
			get
			{
				return this._mavoucher;
			}
			set
			{
				if ((this._mavoucher != value))
				{
					this._mavoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this._ngaybatdau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this._ngayketthuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadontoithieu", DbType="Float")]
		public System.Nullable<double> hoadontoithieu
		{
			get
			{
				return this._hoadontoithieu;
			}
			set
			{
				if ((this._hoadontoithieu != value))
				{
					this._hoadontoithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgiatoida", DbType="Float")]
		public System.Nullable<double> giamgiatoida
		{
			get
			{
				return this._giamgiatoida;
			}
			set
			{
				if ((this._giamgiatoida != value))
				{
					this._giamgiatoida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem2
		{
			get
			{
				return this._ngaythem2;
			}
			set
			{
				if ((this._ngaythem2 != value))
				{
					this._ngaythem2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat2
		{
			get
			{
				return this._ngaycapnhat2;
			}
			set
			{
				if ((this._ngaycapnhat2 != value))
				{
					this._ngaycapnhat2 = value;
				}
			}
		}
	}
	
	public partial class laydulieuvoucherResult
	{
		
		private int _id;
		
		private string _tenvoucher;
		
		private string _mavoucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<double> _hoadontoithieu;
		
		private System.Nullable<double> _giamgiatoida;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		public laydulieuvoucherResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="NVarChar(255)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this._tenvoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavoucher", DbType="VarChar(255)")]
		public string mavoucher
		{
			get
			{
				return this._mavoucher;
			}
			set
			{
				if ((this._mavoucher != value))
				{
					this._mavoucher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this._ngaybatdau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this._ngayketthuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadontoithieu", DbType="Float")]
		public System.Nullable<double> hoadontoithieu
		{
			get
			{
				return this._hoadontoithieu;
			}
			set
			{
				if ((this._hoadontoithieu != value))
				{
					this._hoadontoithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgiatoida", DbType="Float")]
		public System.Nullable<double> giamgiatoida
		{
			get
			{
				return this._giamgiatoida;
			}
			set
			{
				if ((this._giamgiatoida != value))
				{
					this._giamgiatoida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this._ngaythem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
